// <auto-generated />
namespace MVCControllerIntro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class countrymodelupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(countrymodelupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201911261552256_countrymodel-update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
